// <auto-generated />
namespace RuuviTagApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class tagname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tagname));
        
        string IMigrationMetadata.Id
        {
            get { return "202006071408231_tagname"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
